# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 10, 13, 28, 44, 406008)),
        ),
    ]
