# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0002_post_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 3, 7, 12, 55, 14, 904617)),
        ),
    ]
