# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0004_auto_20160310_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='moadben', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 10, 16, 55, 34, 349366)),
        ),
    ]
