# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0005_auto_20160310_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 10, 16, 57, 12, 759937)),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
