# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0009_auto_20160307_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 3, 7, 13, 10, 38, 270137)),
        ),
    ]
