# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0014_auto_20160307_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 3, 7, 16, 58, 59, 290412)),
        ),
    ]
