# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0016_auto_20160307_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 3, 8, 1, 27, 38, 176356)),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=15000),
        ),
    ]
