# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0017_auto_20160308_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 8, 1, 33, 57, 82451)),
        ),
    ]
