# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloqqer', '0018_auto_20160308_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 8, 22, 56, 43, 141297)),
        ),
    ]
